### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by Qonfused** [Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh#18]
(WIP)

##### Main Blockers
Screenpad Plus
- [ ] Display output
- Pre-OS (OpenCore verbose)
    - [x] UEFI GOP
    - [ ] Legacy / CSM
- iGPU Framebuffer
    - [ ] Valid clock data
    - [ ] Proper RGB screenspace
    - [ ] QE/CI acceleration
- [ ] Display metadata (EDID)
    - [ ] Device Name (Cosmetic)
    - [x] Device and Vendor IDs
    - [ ] Valid resolution data
    - [ ] Physical size info (Cosmetic)
- [ ] Touchscreen
    - [x] Basic pointer functionality
    - [ ] Multitouch Gestures
    - [ ] GPIO Pinning (addresses intermittency issue)
- [ ] Backlight control
    - [ ] Leveled slider control
    - [x] Power toggle

Trackpad
- [x] Trackpad functionality
    - [x] Basic pointer functionality
    - [x] Multitouch Gestures
    - [x] Disable force-touch pressure collision (for Recovery)
    - [ ] GPIO Pinning (addresses intermittency issue)
- [ ] Physical buttons
    - [x] Recognize PS2 interface
    - [ ] Proper button mapping

Misc. Interface Devices
- [ ] Primary Display (Touchscreen)
    - [x] Basic pointer functionality
    - [x] Multitouch Gestures
    - [ ] GPIO Pinning (addresses intermittency issue)
- [ ] Capacitive Stylus
    - [ ] Basic pointer functionality

Misc. Audio Devices
- [x] Built-in Speakers
- [ ] Built-in Microphone

IR Devices
- [ ] Windows Hello Camera

**Comment by Qonfused** [comment]
Some additional software features to test/develop for non-opencore targets:
- [ ] Virtual Touchbar ([link to project](https://github.com/sindresorhus/touch-bar-simulator)).
    - [ ] Refactor for compiling to different macOS versions.
- [ ] Fan Control
- (os agnostic)
    - [ ] Create ACPI patch to expose basic fan controls
- Windows
    - [ ] Recover EC writes from MyASUS driver.
    - [ ] Create notebookfancontrol profile (for non-opencore use).
- Linux
    - [ ] Port fan control to ASUS linux driver
- macOS
    - [ ] Expose fan control through AsusSMC kext
    - [ ] Expose fan control through touchbar slider
